version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: carddb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    environment:
      DB_DSN: user:password@tcp(db:3306)/carddb
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db_data:
